/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLogin: typeof import('./../src/views/auth/login.vue')['default']
    AuthRegister: typeof import('./../src/views/auth/register.vue')['default']
    AuthRepassword: typeof import('./../src/views/auth/repassword.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    Front: typeof import('./../src/layout/front.vue')['default']
    Home: typeof import('./../src/views/home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
