/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./../src/layout/admin.vue')['default']
    AdminCategory: typeof import('./../src/views/admin/category/index.vue')['default']
    AdminCategoryAdd: typeof import('./../src/views/admin/category/add.vue')['default']
    AdminCategoryEdit: typeof import('./../src/views/admin/category/edit.vue')['default']
    AdminComment: typeof import('./../src/views/admin/comment/index.vue')['default']
    AdminCommentAdd: typeof import('./../src/views/admin/comment/add.vue')['default']
    AdminCommentEdit: typeof import('./../src/views/admin/comment/edit.vue')['default']
    AdminTopic: typeof import('./../src/views/admin/topic/index.vue')['default']
    AdminTopicAdd: typeof import('./../src/views/admin/topic/add.vue')['default']
    AdminTopicEdit: typeof import('./../src/views/admin/topic/edit.vue')['default']
    AdminUser: typeof import('./../src/views/admin/user/index.vue')['default']
    AnimateList: typeof import('./../src/components/animate/list.vue')['default']
    Auth: typeof import('./../src/layout/auth.vue')['default']
    AuthLogin: typeof import('./../src/views/auth/login.vue')['default']
    AuthRegister: typeof import('./../src/views/auth/register.vue')['default']
    AuthRepassword: typeof import('./../src/views/auth/repassword.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    Error404: typeof import('./../src/views/error/404.vue')['default']
    ErrorAlert: typeof import('./../src/components/error/alert.vue')['default']
    ErrorAlertError: typeof import('./../src/components/errorAlert/error.vue')['default']
    ErrorError: typeof import('./../src/components/error/error.vue')['default']
    Front: typeof import('./../src/layout/front.vue')['default']
    Home: typeof import('./../src/views/home.vue')['default']
    LayoutAvatar: typeof import('./../src/components/layout/avatar.vue')['default']
    LayoutBreadcrumb: typeof import('./../src/components/layout/breadcrumb.vue')['default']
    LayoutBreadcrumbRoute: typeof import('./../src/components/layout/breadcrumbRoute.vue')['default']
    LayoutHistory: typeof import('./../src/components/layout/history.vue')['default']
    LayoutMenu: typeof import('./../src/components/layout/menu.vue')['default']
    List: typeof import('./../src/views/list.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
